不要な記述削除
tubuanha/Bot-base pull request #1
Opened 2021-07-01 12:20 UTC by waki285

package.jsonの不要な記述の削除。

2021-07-01 12:33 UTC, tubuanha requested changes

2021-07-01 12:33 UTC, tubuanha commented on package.json
> +  "name": "Bot-base",
package.jsonの`name`に大文字は使用できません

2021-07-01 12:53 UTC, waki285 commented
おっと、その使用忘れてました

2021-07-02 08:01 UTC, tubuanha approved these changes

2021-07-02 08:02 UTC, merged